project_id = "onhnxxweldxjzhoaiwgq"

[functions.create-tenant-with-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.toggle-user-status]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.dispatch-webhook]
verify_jwt = false

[functions.dispatch-webhook-v2]
verify_jwt = false
